import Head from "next/head";
import {Table} from './components/ui/table';
import {
  Menubar,
  MenubarContent,
  MenubarItem,
  MenubarMenu,
  MenubarSeparator,
  MenubarShortcut,
  MenubarTrigger,
} from "./components/ui/menubar"
import { Button } from "./components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "./components/ui/card"
import { Overview } from "./components/ui/overview";
import React from "react";

interface SensorData {
  id: number;
  name: string;
  value: number;
};

function test() {
  let x = 1 + 1;
  return x == 2;
}

function HelloWorld({value}: {value: number}) {
  const [counter, setCounter] = useState<number>(0);
  const otherValue = 0;

  return <div>Counter: {counter}<button onClick={() => setCounter(prev => prev + 1)}>Counter +</button></div>
}

export default function Home() {


  const [_test_data, setData] = React.useState<SensorData[]>();

  if(_test_data){

    for (let i = 1; i <= 5; i++) {
      const sensorName = `Sensor ${i}`;
      const rvalue = Math.floor(Math.random() * 101);
      const newDataPoint: SensorData = {
        id: i,
        name: sensorName,
        value: rvalue
      };
      
      setData([..._test_data, newDataPoint]);
    }
  }

  const PushSomeData: React.MouseEventHandler = (event) => {
    
    if(_test_data){

      const size: number = _test_data.length;
      const newsize: number = _test_data.length + 1;

      for (let i = size + 1; i <= newsize; i++) {
        const sensorName = `Sensor ${i}`;
        const rvalue = Math.floor(Math.random() * 101);
        const newDataPoint: SensorData = {
          id: i,
          name: sensorName,
          value: rvalue
        };
        
        setData([..._test_data, newDataPoint]);
      }
    }
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >

        <div>

          <Menubar>
            <MenubarMenu>
              <MenubarTrigger>Ansichten</MenubarTrigger>
              <MenubarContent>
                <MenubarItem>
                  New Tab <MenubarShortcut>⌘T</MenubarShortcut>
                </MenubarItem>
                <MenubarItem>Diagramme</MenubarItem>
                <MenubarSeparator />
                <MenubarItem>Tabellen</MenubarItem>
              </MenubarContent>
              <MenubarTrigger>Inputs</MenubarTrigger>
              <MenubarContent>
                <MenubarItem>
                  New Tab <MenubarShortcut>⌘T</MenubarShortcut>
                </MenubarItem>
                <MenubarItem>New Window</MenubarItem>
                <MenubarSeparator />
                <MenubarItem>Share</MenubarItem>
                <MenubarSeparator />
                <MenubarItem>Print</MenubarItem>
              </MenubarContent>
            </MenubarMenu>
          </Menubar>

          <h1 >
            Sniffy
          </h1>

          <div >
           <Card >
              <CardHeader>
                <CardTitle>Sniffy the Sniffing Dog </CardTitle>
                <CardDescription>SNIFFY SNIFFING FOR SOMETHING</CardDescription>
              </CardHeader>
              <CardContent>
                <Overview data={_test_data}/>
              </CardContent>
              <CardFooter >
                <Button variant="outline">Cancel</Button>
                <Button onClick={PushSomeData}>Download RAM</Button>
              </CardFooter>
            </Card>
          </div>
          <HelloWorld value={6}/>

          <div >
            <Card >
              <CardHeader>
                <CardTitle>Sensor 1</CardTitle>
                <CardDescription></CardDescription>
              </CardHeader>
              <CardContent>
                <div >
                  <Table />
                </div>
              </CardContent>
            </Card>
            <Card >
              <CardHeader>
                <CardTitle>Sensor 2</CardTitle>
                <CardDescription></CardDescription>
              </CardHeader>
              <CardContent>
                <div >
                  <Table />
                </div>
              </CardContent>
            </Card>
            <Card >
              <CardHeader>
                <CardTitle>Sensor 3</CardTitle>
                <CardDescription></CardDescription>
              </CardHeader>
              <CardContent>
                <div >
                  <Table />
                </div>
              </CardContent>
            </Card>
            <Card >
              <CardHeader>
                <CardTitle>Sensor 4</CardTitle>
                <CardDescription></CardDescription>
              </CardHeader>
              <CardContent>
                <div >
                  <Table />
                </div>
              </CardContent>
            </Card>
            <Card >
              <CardHeader>
                <CardTitle>Sensor 5</CardTitle>
                <CardDescription></CardDescription>
              </CardHeader>
              <CardContent>
                <div >
                  <Table />
                </div>
              </CardContent>
            </Card>
          </div>

        </div>

      </main>
    </>
  );
}
