import Head from "next/head";
import Link from "next/link";
import BarChartComponent from './BarChart';
import Table from './Table';
import {
  Menubar,
  MenubarContent,
  MenubarItem,
  MenubarMenu,
  MenubarSeparator,
  MenubarShortcut,
  MenubarTrigger,
} from "../../components/ui/menubar"


export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >

        <div>

          <Menubar>
            <MenubarMenu>
              <MenubarTrigger>Ansichten</MenubarTrigger>
              <MenubarContent>
                <MenubarItem>
                  New Tab <MenubarShortcut>⌘T</MenubarShortcut>
                </MenubarItem>
                <MenubarItem>Diagramme</MenubarItem>
                <MenubarSeparator />
                <MenubarItem>Tabellen</MenubarItem>
              </MenubarContent>
              <MenubarTrigger>Inputs</MenubarTrigger>
              <MenubarContent>
                <MenubarItem>
                  New Tab <MenubarShortcut>⌘T</MenubarShortcut>
                </MenubarItem>
                <MenubarItem>New Window</MenubarItem>
                <MenubarSeparator />
                <MenubarItem>Share</MenubarItem>
                <MenubarSeparator />
                <MenubarItem>Print</MenubarItem>
              </MenubarContent>
            </MenubarMenu>
          </Menubar>

          <h1 >
            Create T3 App
          </h1>

          <div >
            <BarChartComponent></BarChartComponent>
          </div>

          <div >
            <div >
              <h2>Item 1</h2>
              <Table></Table>
            </div>
            <div >
              <h2>Item 2</h2>
              <Table></Table>
            </div>
            <div >
              <h2>Item 3</h2>
              <Table></Table>
            </div>
            <div >
              <h2>Item 4</h2>
              <Table></Table>
            </div>
            <div >
              <h2>Item 5</h2>
              <Table></Table>
            </div>
          </div>

        </div>

      </main>
    </>
  );
}
