import Head from "next/head";
import Link from "next/link";
import BarChartComponent from './BarChart';
import {Table} from './components/ui/table';
import {
  Menubar,
  MenubarContent,
  MenubarItem,
  MenubarMenu,
  MenubarSeparator,
  MenubarShortcut,
  MenubarTrigger,
} from "./components/ui/menubar"
import { Button } from "./components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "./components/ui/card"
import { Input } from "./components/ui/input"
import { Label } from "./components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "./components/ui/select"
import { Overview } from "./components/ui/overview";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >

        <div>

          <Menubar>
            <MenubarMenu>
              <MenubarTrigger>Ansichten</MenubarTrigger>
              <MenubarContent>
                <MenubarItem>
                  New Tab <MenubarShortcut>⌘T</MenubarShortcut>
                </MenubarItem>
                <MenubarItem>Diagramme</MenubarItem>
                <MenubarSeparator />
                <MenubarItem>Tabellen</MenubarItem>
              </MenubarContent>
              <MenubarTrigger>Inputs</MenubarTrigger>
              <MenubarContent>
                <MenubarItem>
                  New Tab <MenubarShortcut>⌘T</MenubarShortcut>
                </MenubarItem>
                <MenubarItem>New Window</MenubarItem>
                <MenubarSeparator />
                <MenubarItem>Share</MenubarItem>
                <MenubarSeparator />
                <MenubarItem>Print</MenubarItem>
              </MenubarContent>
            </MenubarMenu>
          </Menubar>

          <h1 >
            Sniffy
          </h1>

          <div >
           <Card className="w-[350px]">
              <CardHeader>
                <CardTitle>Sniffy the Sniffing Dog </CardTitle>
                <CardDescription>SNIFFY SNIFFING FOR SOMETHING</CardDescription>
              </CardHeader>
              <CardContent>
                <Overview />
              </CardContent>
              <CardFooter className="flex justify-between">
                <Button variant="outline">Cancel</Button>
                <Button>Deploy</Button>
              </CardFooter>
            </Card>
          </div>

          <div >
            <div >
              <h2>Item 1</h2>
              <Table></Table>
            </div>
            <div >
              <h2>Item 2</h2>
              <Table></Table>
            </div>
            <div >
              <h2>Item 3</h2>
              <Table></Table>
            </div>
            <div >
              <h2>Item 4</h2>
              <Table></Table>
            </div>
            <div >
              <h2>Item 5</h2>
              <Table></Table>
            </div>
          </div>

        </div>

      </main>
    </>
  );
}
